version: '2'

services: 
    rails:
        image: nu12/pdfglue
        ports: 
            - "80:3000"
        links:
            - "database"
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            
        restart: unless-stopped
    database:
        image: postgres:13.1-alpine
        restart: unless-stopped
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
